id: 8c7b40482bc94071ac223a29d846aac2
title: Toh_558-Destroyer_of_the_Great_Trichiliocosm-v1
type: translation
source_metadata:
  creationtool: 84000-translation-memory
  creationtoolversion: 1.0.0.0
  datatype: PlainText
  segtype: phrase
  adminlang: en
  srclang: bo
  o-tmf: TEI
  creationdate: '2018-07-30T07:33:27.522Z'
  eft-text-id: UT22084-090-002
  eft-text-version: 1.4.2 2020
  xmlns-eft: http://read.84000.co/ns/1.0
